# Generated by Django 4.2.7 on 2025-06-27 06:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iot_gateway1_ip', models.CharField(max_length=50)),
                ('iot_gateway1_port', models.IntegerField()),
                ('iot_gateway2_ip', models.CharField(blank=True, max_length=50, null=True)),
                ('iot_gateway2_port', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'iot_gateway_connection',
            },
        ),
        migrations.CreateModel(
            name='DIValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('di_name', models.CharField(max_length=50)),
                ('di_value', models.FloatField()),
                ('log_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'di_values',
            },
        ),
        migrations.CreateModel(
            name='LeakAppMasterData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(max_length=255)),
                ('greater_less', models.CharField(blank=True, max_length=10, null=True)),
                ('setpoint1', models.IntegerField(blank=True, default=18, null=True)),
                ('value', models.FloatField(blank=True, null=True)),
                ('setpoint2', models.IntegerField(blank=True, default=70, null=True)),
                ('timer1', models.DurationField(blank=True, default=datetime.timedelta(seconds=5), null=True)),
                ('timer2', models.DurationField(blank=True, default=datetime.timedelta(seconds=15), null=True)),
            ],
            options={
                'verbose_name': 'Parts',
                'verbose_name_plural': 'Parts',
                'db_table': 'leakapp_masterdata',
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_name', models.CharField(max_length=50)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
            options={
                'verbose_name': 'Shift',
                'verbose_name_plural': 'Shifts',
                'db_table': 'shift_tbl',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='myplclog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prodstatus', models.IntegerField()),
                ('server_connection_1', models.IntegerField(blank=True, null=True)),
                ('server_connection_2', models.IntegerField(blank=True, null=True)),
                ('part_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leakapp.leakappmasterdata')),
            ],
            options={
                'db_table': 'myplclog',
            },
        ),
        migrations.CreateModel(
            name='LeakAppTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_counter', models.IntegerField()),
                ('filter_values', models.FloatField()),
                ('filter_no', models.CharField(max_length=50, verbose_name='Filter No')),
                ('status', models.CharField(max_length=30)),
                ('highest_value', models.FloatField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('part_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leakapp.leakappmasterdata')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leakapp.shift')),
            ],
            options={
                'verbose_name': 'Leak Test',
                'verbose_name_plural': 'Leak Tests',
                'db_table': 'leakapp_test',
            },
        ),
        migrations.CreateModel(
            name='LeakAppShowReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_counter', models.IntegerField()),
                ('filter_values', models.FloatField()),
                ('filter_no', models.CharField(max_length=50, verbose_name='Filter No')),
                ('status', models.CharField(max_length=30)),
                ('highest_value', models.FloatField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('part_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leakapp.leakappmasterdata')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leakapp.shift')),
            ],
            options={
                'verbose_name': 'Leak Report',
                'verbose_name_plural': 'Leak Report',
                'db_table': 'leakapp_show_report',
            },
        ),
        migrations.CreateModel(
            name='FOIHighest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_counter', models.IntegerField(blank=True, null=True)),
                ('filter_values', models.FloatField()),
                ('filter_no', models.CharField(max_length=50, verbose_name='Filter No')),
                ('status', models.CharField(default='NOK', max_length=30)),
                ('highest_value', models.FloatField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('part_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leakapp.leakappmasterdata')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leakapp.shift')),
            ],
            options={
                'db_table': 'foihighest',
            },
        ),
        migrations.CreateModel(
            name='FOI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_counter', models.IntegerField()),
                ('filter_no', models.CharField(max_length=255)),
                ('filter_values', models.FloatField()),
                ('date', models.DateField()),
                ('shift', models.CharField(blank=True, max_length=25, null=True)),
                ('part_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leakapp.leakappmasterdata', verbose_name='Part Number')),
            ],
            options={
                'verbose_name': 'FOI',
                'verbose_name_plural': 'FOI',
                'db_table': 'foi_tbl',
            },
        ),
        migrations.CreateModel(
            name='LeakAppResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_counter', models.IntegerField(default=0, verbose_name='Batch Counter')),
                ('filter_no', models.CharField(max_length=50)),
                ('filter_values', models.FloatField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('processed', models.BooleanField(default=False)),
                ('part_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leakapp.leakappmasterdata')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leakapp.shift')),
            ],
            options={
                'verbose_name': 'Leak Result',
                'verbose_name_plural': 'Leak Results',
                'db_table': 'leakapp_result_tbl',
                'indexes': [models.Index(fields=['date'], name='leakapp_res_date_2ce05e_idx'), models.Index(fields=['filter_no'], name='leakapp_res_filter__a6904c_idx')],
            },
        ),
    ]
