# Generated by Django 4.2.7 on 2025-07-16 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leakapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myplclog',
            name='server_connection_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='divalues',
            name='di_value',
            field=models.FloatField(),
        ),
    ]
