# Generated by Django 4.2.6 on 2025-04-03 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leakapp', '0022_leakappresult_processed_alter_foihighest_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DIValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('di_name', models.CharField(max_length=50)),
                ('di_value', models.FloatField()),
                ('log_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'di_values',
            },
        ),
        migrations.DeleteModel(
            name='YCalvalues',
        ),
    ]
