# Generated by Django 4.2.6 on 2025-04-04 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leakapp', '0023_divalues_delete_ycalvalues'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iot_gateway1_ip', models.CharField(max_length=50)),
                ('iot_gateway1_port', models.IntegerField()),
                ('iot_gateway2_ip', models.CharField(blank=True, max_length=50, null=True)),
                ('iot_gateway2_port', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'iot_gateway_connection',
            },
        ),
    ]
