# Generated by Django 4.2.6 on 2025-04-04 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leakapp', '0024_connection'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='leakappresult',
            index=models.Index(fields=['date'], name='leakapp_res_date_2ce05e_idx'),
        ),
        migrations.AddIndex(
            model_name='leakappresult',
            index=models.Index(fields=['filter_no'], name='leakapp_res_filter__a6904c_idx'),
        ),
    ]
